language: java
jdk:
  - oraclejdk8
before_script: cd FlightsCrews/  
  
after_success:
- mvn clean test cobertura:cobertura coveralls:report
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
